// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAhCqdpghsv2TU_3KZHwXU07fyqfNCOy0',
    appId: '1:184371780302:web:9a630e187cab0f05588e9f',
    messagingSenderId: '184371780302',
    projectId: 'ctse-labactivity',
    authDomain: 'ctse-labactivity.firebaseapp.com',
    storageBucket: 'ctse-labactivity.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBITtA0UoJ1iTHm9TTfOyFltd-4osspgjk',
    appId: '1:184371780302:android:6fae8286f251ac1a588e9f',
    messagingSenderId: '184371780302',
    projectId: 'ctse-labactivity',
    storageBucket: 'ctse-labactivity.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDovvZX5e0m5-WHmHRrJpyc7o55SFsCh0c',
    appId: '1:184371780302:ios:72290500de2c5bdb588e9f',
    messagingSenderId: '184371780302',
    projectId: 'ctse-labactivity',
    storageBucket: 'ctse-labactivity.appspot.com',
    iosClientId: '184371780302-8fpsvj1prhonfpnsoob68p7mcau3a1g8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ctse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDovvZX5e0m5-WHmHRrJpyc7o55SFsCh0c',
    appId: '1:184371780302:ios:72290500de2c5bdb588e9f',
    messagingSenderId: '184371780302',
    projectId: 'ctse-labactivity',
    storageBucket: 'ctse-labactivity.appspot.com',
    iosClientId: '184371780302-8fpsvj1prhonfpnsoob68p7mcau3a1g8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ctse',
  );
}
